spring:
  datasource:
    url: jdbc:postgresql://10.27.1.114:5432/post_react
    username: postgres
    password: postgres
  jpa:
    open-in-view: true
server:
  port: 8080
  servlet:
      context-path: /post-api
security:
  token_secret: M8hSAIR9gSahUyFED3Ife2ktORagTNae
  token_expiration_time: 86400000
  token_prefix: Bearer
  header_string: Authorization
  sign_up_url: /users
